### PR TITLE
added nsfw bsae will add cmds later

### PR DESCRIPTION
**Pull request by abashir7866**
spent too much time fucking with git clients and i got homwork ill work on it tomorrow

### CODE REVIEW

**Comment by abashir7866** [comment]
Pull!!!

**Comment by abashir7866** [comment]
uwu

**Comment by bentettmar** [comment]
The nsfw command will respond with all the img commands cuz your getting the image commands not the nsfw ones

**Review by bentettmar — CHANGES_REQUESTED** [review]
Change line 20 to walk the commands for "Nsfw" not "Img"

**Comment by abashir7866** [comment]
I skidded from img base ill fix when I get on pc lmao

**Comment by livxy** [comment]
L

**Pull request closed without merging**
